# Analysis on a small sample of the data

In [1]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Set the output length
pd.options.display.max_rows = 500

## Importing and Exploring the data

In [2]:
# Import the first 1000 rows of the data
data = pd.read_csv("venmo.csv", nrows = 500000, low_memory=False)

In [3]:
#Look at the head of the data
data.head()

,_id,date_updated,transfer,app.description,app.site_url,app.image_url,app.id,app.name,comments.count,comments.data.0.date_created,...,authorization.merchant.braintree_merchant_id,authorization.merchant.paypal_merchant_id,authorization.merchant.datetime_updated,authorization.acknowledged,authorization.decline,authorization.id,authorization.captures,authorization.atm_fees,auto_auth_story,user_shared_auth
0,5bb7bd386e52181f090becfa,2018-08-07T02:11:16.000Z,NaN,Venmo for iPhone,NaN,https://venmo.s3.amazonaws.com/oauth/no-image-...,1,Venmo for iPhone,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5bb7bd386e52181f090becfc,2018-08-07T02:11:16.000Z,NaN,Venmo for iPhone,NaN,https://venmo.s3.amazonaws.com/oauth/no-image-...,1,Venmo for iPhone,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5bb7bd386e52181f090becfe,2018-08-07T02:11:15.000Z,NaN,Venmo for Android,NaN,https://venmo.s3.amazonaws.com/oauth/no-image-...,4,Venmo for Android,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5bb7bd386e52181f090bed00,2018-08-07T02:11:15.000Z,NaN,Venmo for iPhone,NaN,https://venmo.s3.amazonaws.com/oauth/no-image-...,1,Venmo for iPhone,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5bb7bd386e52181f090bed02,2018-08-07T02:11:15.000Z,NaN,Venmo for iPhone,NaN,https://venmo.s3.amazonaws.com/oauth/no-image-...,1,Venmo for iPhone,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Look at the different columns
columns = list(data.columns)
column_amount = len(columns)

print("Amount of colums = {}".format(column_amount))

Amount of colums = 404

In [5]:
#Look at the statistics of each column
data.describe()

,transfer,app.id,comments.count,comments.data.0.mentions.count,comments.data.0.mentions.data.0.username,comments.data.0.mentions.data.0.user.username,comments.data.0.mentions.data.0.user.about,comments.data.0.mentions.data.0.user.last_name,comments.data.0.mentions.data.0.user.display_name,comments.data.0.mentions.data.0.user.friends_count,...,authorization.merchant.braintree_merchant_id,authorization.merchant.paypal_merchant_id,authorization.merchant.datetime_updated,authorization.acknowledged,authorization.decline,authorization.id,authorization.captures,authorization.atm_fees,auto_auth_story,user_shared_auth
count,0.0,500000.000000,500000.000000,77.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,6.136094,0.000158,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,75.824023,0.012883,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1809.000000,2.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Shape of the data
data_shape = data.shape

print("The data has {} rows and {} columns".format(data_shape[0], data_shape[1]))

The data has 500000 rows and 404 columns

In [7]:
#Check the types of each column
data.info(memory_usage='deep') # Use verbose=True for full output

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Columns: 404 entries, _id to user_shared_auth
dtypes: bool(3), float64(261), int64(7), object(133)
memory usage: 3.6 GB

In [8]:
#Check for missing values
data.isnull().sum()

_id                                                              0
date_updated                                                     0
transfer                                                    500000
app.description                                                  0
app.site_url                                                498068
app.image_url                                                    0
app.id                                                           0
app.name                                                         0
comments.count                                                   0
comments.data.0.date_created                                499923
comments.data.0.message                                     499923
comments.data.0.mentions.count                              499923
comments.data.0.mentions.data.0.username                    500000
comments.data.0.mentions.data.0.user.username               500000
comments.data.0.mentions.data.0.user.about                  500000
comments.data.0.mentions.data.0.user.last_name              500000
comments.data.0.mentions.data.0.user.display_name           500000
comments.data.0.mentions.data.0.user.friends_count          500000
comments.data.0.mentions.data.0.user.is_group               500000
comments.data.0.mentions.data.0.user.is_active              500000
comments.data.0.mentions.data.0.user.trust_request          500000
comments.data.0.mentions.data.0.user.email                  500000
comments.data.0.mentions.data.0.user.phone                  500000
comments.data.0.mentions.data.0.user.profile_picture_url    500000
comments.data.0.mentions.data.0.user.first_name             500000
comments.data.0.mentions.data.0.user.friend_status          500000
comments.data.0.mentions.data.0.user.is_blocked             500000
comments.data.0.mentions.data.0.user.id                     500000
comments.data.0.mentions.data.0.user.identity               500000
comments.data.0.mentions.data.0.user.date_joined            500000
comments.data.0.id                                          499923
comments.data.0.user.username                               499923
comments.data.0.user.last_name                              499923
comments.data.0.user.friends_count                          500000
comments.data.0.user.is_group                               499923
comments.data.0.user.is_active                              499923
comments.data.0.user.trust_request                          500000
comments.data.0.user.phone                                  500000
comments.data.0.user.profile_picture_url                    499923
comments.data.0.user.is_blocked                             499923
comments.data.0.user.id                                     499923
comments.data.0.user.identity                               500000
comments.data.0.user.date_joined                            499923
comments.data.0.user.about                                  499997
comments.data.0.user.display_name                           499923
comments.data.0.user.first_name                             499923
comments.data.0.user.friend_status                          500000
comments.data.0.user.email                                  500000
comments.data.1.user.username                               499998
comments.data.1.user.about                                  499999
comments.data.1.user.last_name                              499998
comments.data.1.user.display_name                           499998
comments.data.1.user.friends_count                          500000
comments.data.1.user.is_group                               499998
comments.data.1.user.is_active                              499998
comments.data.1.user.trust_request                          500000
comments.data.1.user.email                                  500000
comments.data.1.user.phone                                  500000
comments.data.1.user.profile_picture_url                    499998
comments.data.1.user.first_name                             499998
comments.data.1.user.friend_status                          500000
comments.data.1.user.is_blocked                             499998
comments.data.1.user.id                                     499998
comments.data.1.user.identity                               500000
comments.data.1.user.date_joined                            499998
comments.data.1.date_created                                499998
comments.data.1.message                                     499998
comments.data.1.id                                          499998
comments.data.1.mentions.count                              499998
comments.data.1.mentions.data                               499998
payment.status                                                   0
payment.id                                                       0
payment.date_authorized                                     500000
payment.merchant_split_purchase.authorization_id            499976
payment.merchant_split_purchase.merchant_name               499976
payment.date_completed                                        3496
payment.target.merchant                                     500000
payment.target.redeemable_target.type                       498996
payment.target.redeemable_target.display_name               498996
payment.target.phone                                        500000
payment.target.user.username                                  3497
payment.target.user.last_name                                 3891
payment.target.user.friends_count                           500000
payment.target.user.is_group                                  3497
payment.target.user.is_active                                 3497
payment.target.user.trust_request                           500000
payment.target.user.phone                                   500000
payment.target.user.profile_picture_url                       3497
payment.target.user.is_blocked                                3497
payment.target.user.id                                        3497
payment.target.user.identity                                500000
payment.target.user.date_joined                               3497
payment.target.user.about                                   479489
payment.target.user.display_name                              3497
payment.target.user.first_name                                3887
payment.target.user.friend_status                           500000
payment.target.user.email                                   500000
payment.target.type                                              0
payment.target.email                                        500000
payment.audience                                                 0
payment.actor.username                                           1
payment.actor.last_name                                         52
payment.actor.friends_count                                 500000
payment.actor.is_group                                           0
payment.actor.is_active                                          0
payment.actor.trust_request                                 500000
payment.actor.phone                                         500000
payment.actor.profile_picture_url                                0
payment.actor.is_blocked                                         0
payment.actor.id                                                 0
payment.actor.identity                                      500000
payment.actor.date_joined                                        1
payment.actor.about                                         479344
payment.actor.display_name                                       0
payment.actor.first_name                                        55
payment.actor.friend_status                                 500000
payment.actor.email                                         500000
payment.actor.is_groep                                      500000
payment.note                                                     5
payment.amount                                              500000
payment.action                                                   0
payment.date_created                                             0
payment.date_reminded                                       500000
note                                                             5
audience                                                         0
likes.count                                                      0
likes.data.0.username                                       499421
likes.data.0.last_name                                      499421
likes.data.0.friends_count                                  500000
likes.data.0.is_group                                       499421
likes.data.0.is_active                                      499421
likes.data.0.trust_request                                  500000
likes.data.0.phone                                          500000
likes.data.0.profile_picture_url                            499421
likes.data.0.is_blocked                                     499421
likes.data.0.id                                             499421
likes.data.0.identity                                       500000
likes.data.0.date_joined                                    499421
likes.data.0.about                                          499984
likes.data.0.display_name                                   499421
likes.data.0.first_name                                     499421
likes.data.0.friend_status                                  500000
likes.data.0.email                                          500000
likes.data.1.username                                       499999
likes.data.1.about                                          500000
likes.data.1.last_name                                      499999
likes.data.1.display_name                                   499999
likes.data.1.friends_count                                  500000
likes.data.1.is_group                                       499999
likes.data.1.is_active                                      499999
likes.data.1.trust_request                                  500000
likes.data.1.email                                          500000
likes.data.1.phone                                          500000
likes.data.1.profile_picture_url                            499999
likes.data.1.first_name                                     499999
likes.data.1.friend_status                                  500000
likes.data.1.is_blocked                                     499999
likes.data.1.id                                             499999
likes.data.1.identity                                       500000
likes.data.1.date_joined                                    499999
mentions.count                                                   0
mentions.data.0.username                                    499482
mentions.data.0.user.username                               499482
mentions.data.0.user.last_name                              499482
mentions.data.0.user.friends_count                          500000
mentions.data.0.user.is_group                               499482
mentions.data.0.user.is_active                              499482
mentions.data.0.user.trust_request                          500000
mentions.data.0.user.phone                                  500000
mentions.data.0.user.profile_picture_url                    499482
mentions.data.0.user.is_blocked                             499482
mentions.data.0.user.id                                     499482
mentions.data.0.user.identity                               500000
mentions.data.0.user.date_joined                            499482
mentions.data.0.user.about                                  499969
mentions.data.0.user.display_name                           499482
mentions.data.0.user.first_name                             499482
mentions.data.0.user.friend_status                          500000
mentions.data.0.user.email                                  500000
mentions.data.1.username                                    499981
mentions.data.1.user.username                               499981
mentions.data.1.user.last_name                              499981
mentions.data.1.user.friends_count                          500000
mentions.data.1.user.is_group                               499981
mentions.data.1.user.is_active                              499981
mentions.data.1.user.trust_request                          500000
mentions.data.1.user.phone                                  500000
mentions.data.1.user.profile_picture_url                    499981
mentions.data.1.user.is_blocked                             499981
mentions.data.1.user.id                                     499981
mentions.data.1.user.identity                               500000
mentions.data.1.user.date_joined                            499981
mentions.data.1.user.about                                  500000
mentions.data.1.user.display_name                           499981
mentions.data.1.user.first_name                             499981
mentions.data.1.user.friend_status                          500000
mentions.data.1.user.email                                  500000
mentions.data.2.user.display_name                           499998
mentions.data.2.user.friends_count                          500000
mentions.data.2.user.username                               499998
mentions.data.2.user.date_joined                            499998
mentions.data.2.user.friend_status                          500000
mentions.data.2.user.phone                                  500000
mentions.data.2.user.last_name                              499998
mentions.data.2.user.is_blocked                             499998
mentions.data.2.user.profile_picture_url                    499998
mentions.data.2.user.is_group                               499998
mentions.data.2.user.identity                               500000
mentions.data.2.user.email                                  500000
mentions.data.2.user.is_active                              499998
mentions.data.2.user.id                                     499998
mentions.data.2.user.first_name                             499998
mentions.data.2.user.about                                  500000
mentions.data.2.user.trust_request                          500000
mentions.data.2.username                                    499998
mentions.data.3.username                                    499999
mentions.data.3.user.username                               499999
mentions.data.3.user.about                                  500000
mentions.data.3.user.last_name                              499999
mentions.data.3.user.display_name                           499999
mentions.data.3.user.friends_count                          500000
mentions.data.3.user.is_group                               499999
mentions.data.3.user.is_active                              499999
mentions.data.3.user.trust_request                          500000
mentions.data.3.user.email                                  500000
mentions.data.3.user.phone                                  500000
mentions.data.3.user.profile_picture_url                    499999
mentions.data.3.user.first_name                             499999
mentions.data.3.user.friend_status                          500000
mentions.data.3.user.is_blocked                             499999
mentions.data.3.user.id                                     499999
mentions.data.3.user.identity                               500000
mentions.data.3.user.date_joined                            499999
mentions.data.4.username                                    499999
mentions.data.4.user.username                               499999
mentions.data.4.user.about                                  499999
mentions.data.4.user.last_name                              499999
mentions.data.4.user.display_name                           499999
mentions.data.4.user.friends_count                          500000
mentions.data.4.user.is_group                               499999
mentions.data.4.user.is_active                              499999
mentions.data.4.user.trust_request                          500000
mentions.data.4.user.email                                  500000
mentions.data.4.user.phone                                  500000
mentions.data.4.user.profile_picture_url                    499999
mentions.data.4.user.first_name                             499999
mentions.data.4.user.friend_status                          500000
mentions.data.4.user.is_blocked                             499999
mentions.data.4.user.id                                     499999
mentions.data.4.user.identity                               500000
mentions.data.4.user.date_joined                            499999
mentions.data.5.username                                    500000
mentions.data.5.user.username                               500000
mentions.data.5.user.about                                  500000
mentions.data.5.user.last_name                              500000
mentions.data.5.user.display_name                           500000
mentions.data.5.user.friends_count                          500000
mentions.data.5.user.is_group                               500000
mentions.data.5.user.is_active                              500000
mentions.data.5.user.trust_request                          500000
mentions.data.5.user.email                                  500000
mentions.data.5.user.phone                                  500000
mentions.data.5.user.profile_picture_url                    500000
mentions.data.5.user.first_name                             500000
mentions.data.5.user.friend_status                          500000
mentions.data.5.user.is_blocked                             500000
mentions.data.5.user.id                                     500000
mentions.data.5.user.identity                               500000
mentions.data.5.user.date_joined                            500000
mentions.data.6.username                                    500000
mentions.data.6.user.username                               500000
mentions.data.6.user.about                                  500000
mentions.data.6.user.last_name                              500000
mentions.data.6.user.display_name                           500000
mentions.data.6.user.friends_count                          500000
mentions.data.6.user.is_group                               500000
mentions.data.6.user.is_active                              500000
mentions.data.6.user.trust_request                          500000
mentions.data.6.user.email                                  500000
mentions.data.6.user.phone                                  500000
mentions.data.6.user.profile_picture_url                    500000
mentions.data.6.user.first_name                             500000
mentions.data.6.user.friend_status                          500000
mentions.data.6.user.is_blocked                             500000
mentions.data.6.user.id                                     500000
mentions.data.6.user.identity                               500000
mentions.data.6.user.date_joined                            500000
mentions.data.7.username                                    500000
mentions.data.7.user.username                               500000
mentions.data.7.user.about                                  500000
mentions.data.7.user.last_name                              500000
mentions.data.7.user.display_name                           500000
mentions.data.7.user.friends_count                          500000
mentions.data.7.user.is_group                               500000
mentions.data.7.user.is_active                              500000
mentions.data.7.user.trust_request                          500000
mentions.data.7.user.email                                  500000
mentions.data.7.user.phone                                  500000

### Feature selection
A lot of columns are (almost) empty (contain only null values). These columns are not useful for the analysis. Lets select the columns which are.

In [9]:
#Columns with a lot of missing values aren't useful. Let have a look at columns with sufficient data
fraction = 0.1
missing_columns = data.isnull().sum()
#print(missing_columns)
filled_columns = missing_columns[missing_columns < fraction * len(data)]
empty_columns = missing_columns[missing_columns > fraction * len(data)]
filled_columns_list = list(filled_columns.index)
empty_columns_list = list(empty_columns.index)
print(filled_columns)
print("\nfilled_columns list: \n{}".format(filled_columns_list))
#print("\nempty_columns list: \n{}".format(empty_columns_list))
print("\nAmount of columns with low percentage of missing values = {}".format(len(filled_columns)))

_id                                           0
date_updated                                  0
app.description                               0
app.image_url                                 0
app.id                                        0
app.name                                      0
comments.count                                0
payment.status                                0
payment.id                                    0
payment.date_completed                     3496
payment.target.user.username               3497
payment.target.user.last_name              3891
payment.target.user.is_group               3497
payment.target.user.is_active              3497
payment.target.user.profile_picture_url    3497
payment.target.user.is_blocked             3497
payment.target.user.id                     3497
payment.target.user.date_joined            3497
payment.target.user.display_name           3497
payment.target.user.first_name             3887
payment.target.type                           0
payment.audience                              0
payment.actor.username                        1
payment.actor.last_name                      52
payment.actor.is_group                        0
payment.actor.is_active                       0
payment.actor.profile_picture_url             0
payment.actor.is_blocked                      0
payment.actor.id                              0
payment.actor.date_joined                     1
payment.actor.display_name                    0
payment.actor.first_name                     55
payment.note                                  5
payment.action                                0
payment.date_created                          0
note                                          5
audience                                      0
likes.count                                   0
mentions.count                                0
date_created                                  0
type                                          0
id                                            0
dtype: int64

filled_columns list:
['_id', 'date_updated', 'app.description', 'app.image_url', 'app.id', 'app.name', 'comments.count', 'payment.status', 'payment.id', 'payment.date_completed', 'payment.target.user.username', 'payment.target.user.last_name', 'payment.target.user.is_group', 'payment.target.user.is_active', 'payment.target.user.profile_picture_url', 'payment.target.user.is_blocked', 'payment.target.user.id', 'payment.target.user.date_joined', 'payment.target.user.display_name', 'payment.target.user.first_name', 'payment.target.type', 'payment.audience', 'payment.actor.username', 'payment.actor.last_name', 'payment.actor.is_group', 'payment.actor.is_active', 'payment.actor.profile_picture_url', 'payment.actor.is_blocked', 'payment.actor.id', 'payment.actor.date_joined', 'payment.actor.display_name', 'payment.actor.first_name', 'payment.note', 'payment.action', 'payment.date_created', 'note', 'audience', 'likes.count', 'mentions.count', 'date_created', 'type', 'id']

empty_columns list:
['transfer', 'app.site_url', 'comments.data.0.date_created', 'comments.data.0.message', 'comments.data.0.mentions.count', 'comments.data.0.mentions.data.0.username', 'comments.data.0.mentions.data.0.user.username', 'comments.data.0.mentions.data.0.user.about', 'comments.data.0.mentions.data.0.user.last_name', 'comments.data.0.mentions.data.0.user.display_name', 'comments.data.0.mentions.data.0.user.friends_count', 'comments.data.0.mentions.data.0.user.is_group', 'comments.data.0.mentions.data.0.user.is_active', 'comments.data.0.mentions.data.0.user.trust_request', 'comments.data.0.mentions.data.0.user.email', 'comments.data.0.mentions.data.0.user.phone', 'comments.data.0.mentions.data.0.user.profile_picture_url', 'comments.data.0.mentions.data.0.user.first_name', 'comments.data.0.mentions.data.0.user.friend_status', 'comments.data.0.mentions.data.0.user.is_blocked', 'comments.data.0.mentions.data.0.user.id', 'comments.data.0.mentions.data.0.user.identity', 'comments.data.0.mentions.data.0.user.date_joined', 'comments.data.0.id', 'comments.data.0.user.username', 'comments.data.0.user.last_name', 'comments.data.0.user.friends_count', 'comments.data.0.user.is_group', 'comments.data.0.user.is_active', 'comments.data.0.user.trust_request', 'comments.data.0.user.phone', 'comments.data.0.user.profile_picture_url', 'comments.data.0.user.is_blocked', 'comments.data.0.user.id', 'comments.data.0.user.identity', 'comments.data.0.user.date_joined', 'comments.data.0.user.about', 'comments.data.0.user.display_name', 'comments.data.0.user.first_name', 'comments.data.0.user.friend_status', 'comments.data.0.user.email', 'comments.data.1.user.username', 'comments.data.1.user.about', 'comments.data.1.user.last_name', 'comments.data.1.user.display_name', 'comments.data.1.user.friends_count', 'comments.data.1.user.is_group', 'comments.data.1.user.is_active', 'comments.data.1.user.trust_request', 'comments.data.1.user.email', 'comments.data.1.user.phone', 'comments.data.1.user.profile_picture_url', 'comments.data.1.user.first_name', 'comments.data.1.user.friend_status', 'comments.data.1.user.is_blocked', 'comments.data.1.user.id', 'comments.data.1.user.identity', 'comments.data.1.user.date_joined', 'comments.data.1.date_created', 'comments.data.1.message', 'comments.data.1.id', 'comments.data.1.mentions.count', 'comments.data.1.mentions.data', 'payment.date_authorized', 'payment.merchant_split_purchase.authorization_id', 'payment.merchant_split_purchase.merchant_name', 'payment.target.merchant', 'payment.target.redeemable_target.type', 'payment.target.redeemable_target.display_name', 'payment.target.phone', 'payment.target.user.friends_count', 'payment.target.user.trust_request', 'payment.target.user.phone', 'payment.target.user.identity', 'payment.target.user.about', 'payment.target.user.friend_status', 'payment.target.user.email', 'payment.target.email', 'payment.actor.friends_count', 'payment.actor.trust_request', 'payment.actor.phone', 'payment.actor.identity', 'payment.actor.about', 'payment.actor.friend_status', 'payment.actor.email', 'payment.actor.is_groep', 'payment.amount', 'payment.date_reminded', 'likes.data.0.username', 'likes.data.0.last_name', 'likes.data.0.friends_count', 'likes.data.0.is_group', 'likes.data.0.is_active', 'likes.data.0.trust_request', 'likes.data.0.phone', 'likes.data.0.profile_picture_url', 'likes.data.0.is_blocked', 'likes.data.0.id', 'likes.data.0.identity', 'likes.data.0.date_joined', 'likes.data.0.about', 'likes.data.0.display_name', 'likes.data.0.first_name', 'likes.data.0.friend_status', 'likes.data.0.email', 'likes.data.1.username', 'likes.data.1.about', 'likes.data.1.last_name', 'likes.data.1.display_name', 'likes.data.1.friends_count', 'likes.data.1.is_group', 'likes.data.1.is_active', 'likes.data.1.trust_request', 'likes.data.1.email', 'likes.data.1.phone', 'likes.data.1.profile_picture_url', 'likes.data.1.first_name', 'likes.data.1.friend_status', 'likes.data.1.is_blocked', 'likes.data.1.id', 'likes.data.1.identity', 'likes.data.1.date_joined', 'mentions.data.0.username', 'mentions.data.0.user.username', 'mentions.data.0.user.last_name', 'mentions.data.0.user.friends_count', 'mentions.data.0.user.is_group', 'mentions.data.0.user.is_active', 'mentions.data.0.user.trust_request', 'mentions.data.0.user.phone', 'mentions.data.0.user.profile_picture_url', 'mentions.data.0.user.is_blocked', 'mentions.data.0.user.id', 'mentions.data.0.user.identity', 'mentions.data.0.user.date_joined', 'mentions.data.0.user.about', 'mentions.data.0.user.display_name', 'mentions.data.0.user.first_name', 'mentions.data.0.user.friend_status', 'mentions.data.0.user.email', 'mentions.data.1.username', 'mentions.data.1.user.username', 'mentions.data.1.user.last_name', 'mentions.data.1.user.friends_count', 'mentions.data.1.user.is_group', 'mentions.data.1.user.is_active', 'mentions.data.1.user.trust_request', 'mentions.data.1.user.phone', 'mentions.data.1.user.profile_picture_url', 'mentions.data.1.user.is_blocked', 'mentions.data.1.user.id', 'mentions.data.1.user.identity', 'mentions.data.1.user.date_joined', 'mentions.data.1.user.about', 'mentions.data.1.user.display_name', 'mentions.data.1.user.first_name', 'mentions.data.1.user.friend_status', 'mentions.data.1.user.email', 'mentions.data.2.user.display_name', 'mentions.data.2.user.friends_count', 'mentions.data.2.user.username', 'mentions.data.2.user.date_joined', 'mentions.data.2.user.friend_status', 'mentions.data.2.user.phone', 'mentions.data.2.user.last_name', 'mentions.data.2.user.is_blocked', 'mentions.data.2.user.profile_picture_url', 'mentions.data.2.user.is_group', 'mentions.data.2.user.identity', 'mentions.data.2.user.email', 'mentions.data.2.user.is_active', 'mentions.data.2.user.id', 'mentions.data.2.user.first_name', 'mentions.data.2.user.about', 'mentions.data.2.user.trust_request', 'mentions.data.2.username', 'mentions.data.3.username', 'mentions.data.3.user.username', 'mentions.data.3.user.about', 'mentions.data.3.user.last_name', 'mentions.data.3.user.display_name', 'mentions.data.3.user.friends_count', 'mentions.data.3.user.is_group', 'mentions.data.3.user.is_active', 'mentions.data.3.user.trust_request', 'mentions.data.3.user.email', 'mentions.data.3.user.phone', 'mentions.data.3.user.profile_picture_url', 'mentions.data.3.user.first_name', 'mentions.data.3.user.friend_status', 'mentions.data.3.user.is_blocked', 'mentions.data.3.user.id', 'mentions.data.3.user.identity', 'mentions.data.3.user.date_joined', 'mentions.data.4.username', 'mentions.data.4.user.username', 'mentions.data.4.user.about', 'mentions.data.4.user.last_name', 'mentions.data.4.user.display_name', 'mentions.data.4.user.friends_count', 'mentions.data.4.user.is_group', 'mentions.data.4.user.is_active', 'mentions.data.4.user.trust_request', 'mentions.data.4.user.email', 'mentions.data.4.user.phone', 'mentions.data.4.user.profile_picture_url', 'mentions.data.4.user.first_name', 'mentions.data.4.user.friend_status', 'mentions.data.4.user.is_blocked', 'mentions.data.4.user.id', 'mentions.data.4.user.identity', 'mentions.data.4.user.date_joined', 'mentions.data.5.username', 'mentions.data.5.user.username', 'mentions.data.5.user.about', 'mentions.data.5.user.last_name', 'mentions.data.5.user.display_name', 'mentions.data.5.user.friends_count', 'mentions.data.5.user.is_group', 'mentions.data.5.user.is_active', 'mentions.data.5.user.trust_request', 'mentions.data.5.user.email', 'mentions.data.5.user.phone', 'mentions.data.5.user.profile_picture_url', 'mentions.data.5.user.first_name', 'mentions.data.5.user.friend_status', 'mentions.data.5.user.is_blocked', 'mentions.data.5.user.id', 'mentions.data.5.user.identity', 'mentions.data.5.user.date_joined', 'mentions.data.6.username', 'mentions.data.6.user.username', 'mentions.data.6.user.about', 'mentions.data.6.user.last_name', 'mentions.data.6.user.display_name', 'mentions.data.6.user.friends_count', 'mentions.data.6.user.is_group', 'mentions.data.6.user.is_active', 'mentions.data.6.user.trust_request', 'mentions.data.6.user.email', 'mentions.data.6.user.phone', 'mentions.data.6.user.profile_picture_url', 'mentions.data.6.user.first_name', 'mentions.data.6.user.friend_status', 'mentions.data.6.user.is_blocked', 'mentions.data.6.user.id', 'mentions.data.6.user.identity', 'mentions.data.6.user.date_joined', 'mentions.data.7.username', 'mentions.data.7.user.username', 'mentions.data.7.user.about', 'mentions.data.7.user.last_name', 'mentions.data.7.user.display_name', 'mentions.data.7.user.friends_count', 'mentions.data.7.user.is_group', 'mentions.data.7.user.is_active', 'mentions.data.7.user.trust_request', 'mentions.data.7.user.email', 'mentions.data.7.user.phone', 'mentions.data.7.user.profile_picture_url', 'mentions.data.7.user.first_name', 'mentions.data.7.user.friend_status', 'mentions.data.7.user.is_blocked', 'mentions.data.7.user.id', 'mentions.data.7.user.identity', 'mentions.data.7.user.date_joined', 'mentions.data.8.username', 'mentions.data.8.user.username', 'mentions.data.8.user.about', 'mentions.data.8.user.last_name', 'mentions.data.8.user.display_name', 'mentions.data.8.user.friends_count', 'mentions.data.8.user.is_group', 'mentions.data.8.user.is_active', 'mentions.data.8.user.trust_request', 'mentions.data.8.user.email', 'mentions.data.8.user.phone', 'mentions.data.8.user.profile_picture_url', 'mentions.data.8.user.first_name', 'mentions.data.8.user.friend_status', 'mentions.data.8.user.is_blocked', 'mentions.data.8.user.id', 'mentions.data.8.user.identity', 'mentions.data.8.user.date_joined', 'mentions.data.9.username', 'mentions.data.9.user.username', 'mentions.data.9.user.about', 'mentions.data.9.user.last_name', 'mentions.data.9.user.display_name', 'mentions.data.9.user.friends_count', 'mentions.data.9.user.is_group', 'mentions.data.9.user.is_active', 'mentions.data.9.user.trust_request', 'mentions.data.9.user.email', 'mentions.data.9.user.phone', 'mentions.data.9.user.profile_picture_url', 'mentions.data.9.user.first_name', 'mentions.data.9.user.friend_status', 'mentions.data.9.user.is_blocked', 'mentions.data.9.user.id', 'mentions.data.9.user.identity', 'mentions.data.9.user.date_joined', 'mentions.data.10.username', 'mentions.data.10.user.username', 'mentions.data.10.user.last_name', 'mentions.data.10.user.friends_count', 'mentions.data.10.user.is_group', 'mentions.data.10.user.is_active', 'mentions.data.10.user.trust_request', 'mentions.data.10.user.phone', 'mentions.data.10.user.profile_picture_url', 'mentions.data.10.user.is_blocked', 'mentions.data.10.user.id', 'mentions.data.10.user.identity', 'mentions.data.10.user.date_joined', 'mentions.data.10.user.about', 'mentions.data.10.user.display_name', 'mentions.data.10.user.first_name', 'mentions.data.10.user.friend_status', 'mentions.data.10.user.email', 'authorization.created_at', 'authorization.amount', 'authorization.authorization_types', 'authorization.user.username', 'authorization.user.friends_count', 'authorization.user.is_active', 'authorization.user.display_name', 'authorization.user.friend_status', 'authorization.user.email', 'authorization.user.first_name', 'authorization.user.identity', 'authorization.user.last_name', 'authorization.user.is_blocked', 'authorization.user.about', 'authorization.user.profile_picture_url', 'authorization.user.id', 'authorization.user.phone', 'authorization.user.trust_request', 'authorization.user.date_joined', 'authorization.user.is_group', 'authorization.story_id', 'authorization.payment_method', 'authorization.point_of_sale.city', 'authorization.point_of_sale.state', 'authorization.is_venmo_card', 'authorization.descriptor', 'authorization.status', 'authorization.merchant.image_url', 'authorization.merchant.display_name', 'authorization.merchant.id', 'authorization.merchant.image_datetime_updated', 'authorization.merchant.datetime_created', 'authorization.merchant.braintree_merchant_id', 'authorization.merchant.paypal_merchant_id', 'authorization.merchant.datetime_updated', 'authorization.acknowledged', 'authorization.decline', 'authorization.id', 'authorization.captures', 'authorization.atm_fees', 'auto_auth_story', 'user_shared_auth']

Amount of columns with low percentage of missing values = 42

### Drop the null columns

In [10]:
#Create a new dataframe with the filled columns only
#data = pd.read_csv("venmo.csv", nrows = 1000000, usecols=filled_columns_list)
data.drop(empty_columns_list, axis = 1, inplace=True)

In [11]:
#Lets get some info on this data to
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 42 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   _id                                      500000 non-null  object
 1   date_updated                             500000 non-null  object
 2   app.description                          500000 non-null  object
 3   app.image_url                            500000 non-null  object
 4   app.id                                   500000 non-null  int64
 5   app.name                                 500000 non-null  object
 6   comments.count                           500000 non-null  int64
 7   payment.status                           500000 non-null  object
 8   payment.id                               500000 non-null  int64
 9   payment.date_completed                   496504 non-null  object
 10  payment.target.user.username             496503 non-null  object
 11  payment.target.user.last_name            496109 non-null  object
 12  payment.target.user.is_group             496503 non-null  object
 13  payment.target.user.is_active            496503 non-null  object
 14  payment.target.user.profile_picture_url  496503 non-null  object
 15  payment.target.user.is_blocked           496503 non-null  object
 16  payment.target.user.id                   496503 non-null  float64
 17  payment.target.user.date_joined          496503 non-null  object
 18  payment.target.user.display_name         496503 non-null  object
 19  payment.target.user.first_name           496113 non-null  object
 20  payment.target.type                      500000 non-null  object
 21  payment.audience                         500000 non-null  object
 22  payment.actor.username                   499999 non-null  object
 23  payment.actor.last_name                  499948 non-null  object
 24  payment.actor.is_group                   500000 non-null  bool
 25  payment.actor.is_active                  500000 non-null  bool
 26  payment.actor.profile_picture_url        500000 non-null  object
 27  payment.actor.is_blocked                 500000 non-null  bool
 28  payment.actor.id                         500000 non-null  int64
 29  payment.actor.date_joined                499999 non-null  object
 30  payment.actor.display_name               500000 non-null  object
 31  payment.actor.first_name                 499945 non-null  object
 32  payment.note                             499995 non-null  object
 33  payment.action                           500000 non-null  object
 34  payment.date_created                     500000 non-null  object
 35  note                                     499995 non-null  object
 36  audience                                 500000 non-null  object
 37  likes.count                              500000 non-null  int64
 38  mentions.count                           500000 non-null  int64
 39  date_created                             500000 non-null  object
 40  type                                     500000 non-null  object
 41  id                                       500000 non-null  int64
dtypes: bool(3), float64(1), int64(7), object(31)
memory usage: 1.1 GB

We can see that we have 4 data types: bool (3x), float64 (1x), int64 (7x) and object (31x)

## Optimize integer data types columns

In [12]:
#Let us optimize the integer data types
#Describe the data
data.select_dtypes(include='int').describe().round(1)

,app.id,comments.count,payment.id,payment.actor.id,likes.count,mentions.count,id
count,500000.0,500000.0,5.000000e+05,5.000000e+05,500000.0,500000.0,5.000000e+05
mean,6.1,0.0,2.533735e+18,1.990255e+18,0.0,0.0,2.533735e+18
std,75.8,0.0,8.042919e+14,3.359236e+17,0.0,0.0,8.042919e+14
min,1.0,0.0,2.532209e+18,1.747412e+17,0.0,0.0,2.532209e+18
25%,1.0,0.0,2.533083e+18,1.755397e+18,0.0,0.0,2.533083e+18
50%,1.0,0.0,2.533748e+18,2.026399e+18,0.0,0.0,2.533748e+18
75%,1.0,0.0,2.534419e+18,2.267114e+18,0.0,0.0,2.534419e+18
max,1809.0,2.0,2.540405e+18,2.535105e+18,2.0,5.0,2.540405e+18

We see that the app.id, comments.count, likes.count and mentions.count have a very small range. These data types don't have to be int64, we can convert them to uint8 (unsigned int 8 bits).

In [13]:
#Convert data type of some integer columns
data["app.id"] = data["app.id"].astype("uint16")
data["comments.count"] = data["comments.count"].astype("uint8")
data["likes.count"] = data["likes.count"].astype("uint8")
data["mentions.count"] = data["mentions.count"].astype("uint8")

## Optimize object data types columns

Lets look at the object data types colums.

In [14]:
data.select_dtypes(include="object").head()

,_id,date_updated,app.description,app.image_url,app.name,payment.status,payment.date_completed,payment.target.user.username,payment.target.user.last_name,payment.target.user.is_group,...,payment.actor.date_joined,payment.actor.display_name,payment.actor.first_name,payment.note,payment.action,payment.date_created,note,audience,date_created,type
0,5bb7bd386e52181f090becfa,2018-08-07T02:11:16.000Z,Venmo for iPhone,https://venmo.s3.amazonaws.com/oauth/no-image-...,Venmo for iPhone,settled,2018-08-07T02:11:16,kimsionie,Kim,False,...,2018-05-19T18:00:04.000Z,Vitna Kim,Vitna,fuk ya,pay,2018-08-07T02:11:16,fuk ya,public,2018-08-07T02:11:16.000Z,payment
1,5bb7bd386e52181f090becfc,2018-08-07T02:11:16.000Z,Venmo for iPhone,https://venmo.s3.amazonaws.com/oauth/no-image-...,Venmo for iPhone,settled,2018-08-07T02:11:16,Kari-Joel-1,Joel,False,...,2017-12-05T20:44:55.000Z,Brian Joel,Brian,:venmo_dollar:,pay,2018-08-07T02:11:16,:venmo_dollar:,public,2018-08-07T02:11:16.000Z,payment
2,5bb7bd386e52181f090becfe,2018-08-07T02:11:15.000Z,Venmo for Android,https://venmo.s3.amazonaws.com/oauth/no-image-...,Venmo for Android,settled,2018-08-07T02:11:15,JDR88,Rankin,False,...,2017-08-10T02:59:07.000Z,Savannah Landry,Savannah,🎉,pay,2018-08-07T02:11:15,🎉,public,2018-08-07T02:11:15.000Z,payment
3,5bb7bd386e52181f090bed00,2018-08-07T02:11:15.000Z,Venmo for iPhone,https://venmo.s3.amazonaws.com/oauth/no-image-...,Venmo for iPhone,settled,2018-08-07T02:11:15,Dion-Nunez,Nunez,False,...,2016-11-16T18:56:55.000Z,Brittany Gross,Brittany,Boyz,charge,2018-08-07T02:11:15,Boyz,public,2018-08-07T02:11:15.000Z,payment
4,5bb7bd386e52181f090bed02,2018-08-07T02:11:15.000Z,Venmo for iPhone,https://venmo.s3.amazonaws.com/oauth/no-image-...,Venmo for iPhone,settled,2018-08-07T02:11:15,AlecJameson,Jameson,False,...,2016-08-31T22:48:24.000Z,Trey Hill,Trey,🥩,pay,2018-08-07T02:11:15,🥩,public,2018-08-07T02:11:15.000Z,payment

Lets see the amount of unique values per column for the object columns.

In [15]:
data.select_dtypes(include="object").nunique()

_id                                        500000
date_updated                                94963
app.description                                 8
app.image_url                                   1
app.name                                        8
payment.status                                  3
payment.date_completed                      95314
payment.target.user.username               445873
payment.target.user.last_name              131321
payment.target.user.is_group                    2
payment.target.user.is_active                   1
payment.target.user.profile_picture_url    361050
payment.target.user.is_blocked                  1
payment.target.user.date_joined            444851
payment.target.user.display_name           409442
payment.target.user.first_name              42463
payment.target.type                             4
payment.audience                                1
payment.actor.username                     457585
payment.actor.last_name                    132809
payment.actor.profile_picture_url          369780
payment.actor.date_joined                  456499
payment.actor.display_name                 419636
payment.actor.first_name                    41956
payment.note                               242318
payment.action                                  2
payment.date_created                        94992
note                                       242319
audience                                        1
date_created                                94992
type                                            1
dtype: int64

In [16]:
#Looking at unique values of the object columns
for column in data.select_dtypes(include="object").columns:
    print("------------------------------------------------------------------------------------------------------------------------------")
    print("{}\n".format(column))
    print(data[column].value_counts())
    print("\n")

------------------------------------------------------------------------------------------------------------------------------
_id

5bb7bea11bed297da9003652    1
5bb7bf211bed297da90256e5    1
5bb7be451bed297da9feb078    1
5bb7bf551bed297da90332c0    1
5bb7bfad1bed297da904a949    1
                           ..
5bb7be111bed297da9fdd107    1
5bb7be431bed297da9fea59f    1
5bb7be0e1bed297da9fdc6f7    1
5bb7be6e1bed297da9ff5cd9    1
5bb7bf2b1bed297da90280e2    1
Name: _id, Length: 500000, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
date_updated

2018-07-27T21:56:06.000Z    38
2018-07-28T00:52:56.000Z    32
2018-07-27T23:11:40.000Z    32
2018-07-27T21:20:20.000Z    31
2018-07-28T01:03:31.000Z    31
                            ..
2018-07-28T08:29:54.000Z     1
2018-07-28T10:31:18.000Z     1
2018-07-30T08:46:26.000Z     1
2018-07-30T09:04:58.000Z     1
2018-07-28T09:34:03.000Z     1
Name: date_updated, Length: 94963, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
app.description

Venmo for iPhone                                                                                       432765
Venmo for Android                                                                                       64737
Share bills and IOUs. Make sure everyone gets paid back. Totally free for web, iPhone, and Android.      1902
Venmo.com                                                                                                 552
Makes splitting restaurant/bar bills easy; facilitates payments between people in the group.               30
Payouts API                                                                                                12
Automation                                                                                                  1
Venmo payments for the WP platform.                                                                         1
Name: app.description, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
app.image_url

https://venmo.s3.amazonaws.com/oauth/no-image-100x100.png    500000
Name: app.image_url, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
app.name

Venmo for iPhone     432765
Venmo for Android     64737
splitwise              1902
Venmo.com               552
tab                      30
venmo payouts            12
Workflow                  1
Pay.mo                    1
Name: app.name, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.status

settled      496503
pending        3489
cancelled         8
Name: payment.status, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.date_completed

2018-07-27T23:11:40    31
2018-07-28T01:03:31    31
2018-07-27T21:20:20    29
2018-07-28T00:52:56    29
2018-07-28T19:10:25    28
                       ..
2018-07-30T11:02:46     1
2018-07-29T12:21:56     1
2018-07-30T09:01:36     1
2018-07-29T12:57:03     1
2018-07-30T06:38:12     1
Name: payment.date_completed, Length: 95314, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.username

Shea-Serrano        47
barb-dwyer          29
Factory-DTLA        23
LibertyontheLake    23
Corbo-Corbo         20
                    ..
Lisahoang256         1
apsarasankar         1
srgerberich          1
AndreaSaltz          1
ely3gonzalez3        1
Name: payment.target.user.username, Length: 445873, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.last_name

Smith         2681
Lee           2017
Nguyen        1962
Johnson       1961
Brown         1573
              ...
Jakubas          1
Mondesire        1
Pawek            1
Capizzelli       1
Fives            1
Name: payment.target.user.last_name, Length: 131321, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.is_group

False    496113
True        390
Name: payment.target.user.is_group, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.is_active

True    496503
Name: payment.target.user.is_active, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.profile_picture_url

https://s3.amazonaws.com/venmo/no-image.gif                                  92666
https://s3.amazonaws.com/venmo/placeholder-image/groups-placeholder.svg         75
https://graph.facebook.com/v2.10/10207268436973932/picture?type=square          47
https://venmopics.appspot.com/u/v1/s/52ab0a98-91d4-40da-80f9-d8e39336892e       29
https://venmopics.appspot.com/u/v1/s/a2621971-65b5-4a23-9b67-cbbce47c5491       23
                                                                             ...
https://venmopics.appspot.com/u/v2/s/f9a56e09-471a-413f-bf89-6e15b0bbdcf2        1
https://venmopics.appspot.com/u/v1/s/9fea6bf9-449a-4b10-9686-6973de3b4444        1
https://venmopics.appspot.com/u/v1/s/58ffe367-0275-423f-8e6a-79ae140eb188        1
https://venmopics.appspot.com/u/v2/f/645b053e-d542-4bb7-9766-32b09979e20e        1
https://venmopics.appspot.com/u/v1/f/e868666d-8128-4987-9c86-9e71c326026b        1
Name: payment.target.user.profile_picture_url, Length: 361050, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.is_blocked

False    496503
Name: payment.target.user.is_blocked, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.date_joined

2015-07-13T20:31:59    47
2016-11-10T17:18:13    29
2018-06-04T17:18:16    23
2018-05-31T15:34:42    23
2015-02-12T09:04:34    20
                       ..
2015-01-13T15:14:53     1
2016-10-11T14:46:09     1
2017-12-29T00:36:35     1
2017-02-04T18:36:23     1
2014-07-08T18:06:26     1
Name: payment.target.user.date_joined, Length: 444851, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.display_name

Shea Serrano         47
Ryan Smith           42
Kevin Nguyen         40
Tyler Smith          30
Barbara Dwyer        29
                     ..
Jonathan Lockhart     1
Tommy Maletta         1
Michael Snader        1
Aliona Reselian       1
Zoe Anne              1
Name: payment.target.user.display_name, Length: 409442, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.user.first_name

Michael        4778
Ryan           3980
Emily          3849
Alex           3704
Sarah          3671
               ...
Akeisha           1
Marvin Ware       1
Ebilade           1
Huyy              1
bhavik            1
Name: payment.target.user.first_name, Length: 42463, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.target.type

user          496503
email           1285
phone           1208
redeemable      1004
Name: payment.target.type, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.audience

public    500000
Name: payment.audience, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.actor.username

BenGarvis            30
isaac-gray           27
davilan              20
Wenbo-Wang-1         17
LauraNevin           16
                     ..
SerenaPacheco_        1
lolaope               1
reidquinntana         1
Denis-Bajric          1
Aaron-Kaczmarek-1     1
Name: payment.actor.username, Length: 457585, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.actor.last_name

Smith        2850
Johnson      2042
Lee          2036
Nguyen       1952
Miller       1562
             ...
Courtot         1
Shamas          1
Diocales        1
Bernards        1
Telthorst       1
Name: payment.actor.last_name, Length: 132809, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.actor.profile_picture_url

https://s3.amazonaws.com/venmo/no-image.gif                                  94049
https://venmopics.appspot.com/u/v1/s/a88fe4de-60d8-4196-9be7-548e6e710da5       30
https://venmopics.appspot.com/u/v3/s/110f6e18-464d-431a-bbc9-e7464d3206f4       27
https://venmopics.appspot.com/u/v1/s/70553c58-0a78-4ee1-b6fa-3b4ce6dd652d       17
https://venmopics.appspot.com/u/v3/s/daadc4a0-26e3-432d-94d9-9fe2acd4f77c       16
                                                                             ...
https://graph.facebook.com/v2.10/10206277470908209/picture?type=square           1
https://venmopics.appspot.com/u/v3/s/dd101935-7063-40fa-9d44-90cba602e12c        1
https://venmopics.appspot.com/u/v1/s/f48c9760-e28e-47e1-9fad-6691c94b4d22        1
https://venmopics.appspot.com/u/v3/f/ccea3295-aa8b-415d-a6a3-2faa6235bb53        1
https://venmopics.appspot.com/u/v1/s/38f00c84-929e-4128-85d4-e9fb75b5b934        1
Name: payment.actor.profile_picture_url, Length: 369780, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.actor.date_joined

2015-12-03T17:08:46    30
2014-08-26T02:13:08    27
2017-01-24T21:55:54    20
2015-08-30T03:14:03    17
2014-07-11T00:18:52    16
                       ..
2017-12-11T22:16:07     1
2016-07-05T17:49:14     1
2016-06-11T18:33:22     1
2014-09-18T23:11:29     1
2016-05-04T19:09:12     1
Name: payment.actor.date_joined, Length: 456499, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.actor.display_name

Daniel Lee                 41
Kevin Nguyen               36
David Kim                  32
Ashley Smith               31
Daniel Kim                 31
                           ..
Cesar Delgado Rodriguez     1
Sophia Ederaine             1
Joseph Ciccio               1
Drew Zimmerman              1
Mac Mendelovici             1
Name: payment.actor.display_name, Length: 419636, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.actor.first_name

Michael     4504
Emily       4036
Sarah       3945
Ryan        3683
Alex        3673
            ...
Dubraska       1
aarash         1
WaiLam         1
Ai Nhu         1
Tairay         1
Name: payment.actor.first_name, Length: 41956, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.note

Food                      5525
Uber                      4575
🏠💸                        4478
🍕                         4432
⛽                         2798
                          ...
dead guy on the subway       1
water!!!!!                   1
🤷🏽‍♀️🤫                       1
🍷🍷🍷🍷🍷🍷🍷☕️                    1
Alex’s tavern                1
Name: payment.note, Length: 242318, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.action

pay       426200
charge     73800
Name: payment.action, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
payment.date_created

2018-07-27T21:56:06    38
2018-07-27T23:11:40    32
2018-07-28T00:52:56    32
2018-07-28T01:03:31    31
2018-07-27T21:20:20    31
                       ..
2018-07-30T07:01:31     1
2018-07-30T08:56:41     1
2018-07-28T10:20:05     1
2018-07-30T03:52:59     1
2018-07-27T08:48:03     1
Name: payment.date_created, Length: 94992, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
note

Food                      5525
Uber                      4575
🏠💸                        4478
🍕                         4432
⛽                         2798
                          ...
dead guy on the subway       1
water!!!!!                   1
🤷🏽‍♀️🤫                       1
🍷🍷🍷🍷🍷🍷🍷☕️                    1
Alex’s tavern                1
Name: note, Length: 242319, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
audience

public    500000
Name: audience, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
date_created

2018-07-27T21:56:06.000Z    38
2018-07-28T00:52:56.000Z    32
2018-07-27T23:11:40.000Z    32
2018-07-27T21:20:20.000Z    31
2018-07-28T01:03:31.000Z    31
                            ..
2018-07-29T08:32:55.000Z     1
2018-07-27T07:24:59.000Z     1
2018-07-27T09:48:22.000Z     1
2018-07-27T08:08:08.000Z     1
2018-07-29T10:57:10.000Z     1
Name: date_created, Length: 94992, dtype: int64


------------------------------------------------------------------------------------------------------------------------------
type

payment    500000
Name: type, dtype: int64

In [17]:
#Dropping the following columns
drop_columns = ["_id", "app.image_url", "app.description", "payment.audience", "audience", "type"]

In [18]:
data.drop(drop_columns, axis = 1, inplace=True)

In [19]:
len(data.columns)

36

In [20]:
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 36 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   date_updated                             500000 non-null  object
 1   app.id                                   500000 non-null  uint8
 2   app.name                                 500000 non-null  object
 3   comments.count                           500000 non-null  uint8
 4   payment.status                           500000 non-null  object
 5   payment.id                               500000 non-null  int64
 6   payment.date_completed                   496504 non-null  object
 7   payment.target.user.username             496503 non-null  object
 8   payment.target.user.last_name            496109 non-null  object
 9   payment.target.user.is_group             496503 non-null  object
 10  payment.target.user.is_active            496503 non-null  object
 11  payment.target.user.profile_picture_url  496503 non-null  object
 12  payment.target.user.is_blocked           496503 non-null  object
 13  payment.target.user.id                   496503 non-null  float64
 14  payment.target.user.date_joined          496503 non-null  object
 15  payment.target.user.display_name         496503 non-null  object
 16  payment.target.user.first_name           496113 non-null  object
 17  payment.target.type                      500000 non-null  object
 18  payment.actor.username                   499999 non-null  object
 19  payment.actor.last_name                  499948 non-null  object
 20  payment.actor.is_group                   500000 non-null  bool
 21  payment.actor.is_active                  500000 non-null  bool
 22  payment.actor.profile_picture_url        500000 non-null  object
 23  payment.actor.is_blocked                 500000 non-null  bool
 24  payment.actor.id                         500000 non-null  int64
 25  payment.actor.date_joined                499999 non-null  object
 26  payment.actor.display_name               500000 non-null  object
 27  payment.actor.first_name                 499945 non-null  object
 28  payment.note                             499995 non-null  object
 29  payment.action                           500000 non-null  object
 30  payment.date_created                     500000 non-null  object
 31  note                                     499995 non-null  object
 32  likes.count                              500000 non-null  uint8
 33  mentions.count                           500000 non-null  uint8
 34  date_created                             500000 non-null  object
 35  id                                       500000 non-null  int64
dtypes: bool(3), float64(1), int64(3), object(25), uint8(4)
memory usage: 866.3 MB

In [21]:
#Data to be imported when using read_csv
final_columns = list(data.columns)
print(final_columns)

['date_updated', 'app.id', 'app.name', 'comments.count', 'payment.status', 'payment.id', 'payment.date_completed', 'payment.target.user.username', 'payment.target.user.last_name', 'payment.target.user.is_group', 'payment.target.user.is_active', 'payment.target.user.profile_picture_url', 'payment.target.user.is_blocked', 'payment.target.user.id', 'payment.target.user.date_joined', 'payment.target.user.display_name', 'payment.target.user.first_name', 'payment.target.type', 'payment.actor.username', 'payment.actor.last_name', 'payment.actor.is_group', 'payment.actor.is_active', 'payment.actor.profile_picture_url', 'payment.actor.is_blocked', 'payment.actor.id', 'payment.actor.date_joined', 'payment.actor.display_name', 'payment.actor.first_name', 'payment.note', 'payment.action', 'payment.date_created', 'note', 'likes.count', 'mentions.count', 'date_created', 'id']